/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PortalPostsRouteImport } from './routes/portal/posts'
import { Route as PortalAuthRouteImport } from './routes/portal/_auth'
import { Route as PortalPostsPostIdRouteImport } from './routes/portal/posts_.$postId'
import { Route as PortalAuthTodosRouteImport } from './routes/portal/_auth/todos'
import { Route as PortalAuthProductsRouteImport } from './routes/portal/_auth/products'
import { Route as PortalPostsPostIdCommentsRouteImport } from './routes/portal/posts_.$postId.comments'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PortalPostsRoute = PortalPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostsPostIdRoute = PortalPostsPostIdRouteImport.update({
  id: '/posts_/$postId',
  path: '/posts/$postId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuthTodosRoute = PortalAuthTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => PortalAuthRoute,
} as any)
const PortalAuthProductsRoute = PortalAuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PortalAuthRoute,
} as any)
const PortalPostsPostIdCommentsRoute =
  PortalPostsPostIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => PortalPostsPostIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalAuthRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/portal/posts': typeof PortalPostsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portal/': typeof PortalIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/portal/products': typeof PortalAuthProductsRoute
  '/portal/todos': typeof PortalAuthTodosRoute
  '/portal/posts/$postId': typeof PortalPostsPostIdRouteWithChildren
  '/portal/posts/$postId/comments': typeof PortalPostsPostIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/posts': typeof PortalPostsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile': typeof ProfileIndexRoute
  '/portal/products': typeof PortalAuthProductsRoute
  '/portal/todos': typeof PortalAuthTodosRoute
  '/portal/posts/$postId': typeof PortalPostsPostIdRouteWithChildren
  '/portal/posts/$postId/comments': typeof PortalPostsPostIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/portal/_auth': typeof PortalAuthRouteWithChildren
  '/portal/posts': typeof PortalPostsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portal/': typeof PortalIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/portal/_auth/products': typeof PortalAuthProductsRoute
  '/portal/_auth/todos': typeof PortalAuthTodosRoute
  '/portal/posts_/$postId': typeof PortalPostsPostIdRouteWithChildren
  '/portal/posts_/$postId/comments': typeof PortalPostsPostIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/profile'
    | '/portal/posts'
    | '/profile/edit'
    | '/portal/'
    | '/profile/'
    | '/portal/products'
    | '/portal/todos'
    | '/portal/posts/$postId'
    | '/portal/posts/$postId/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/portal/posts'
    | '/profile/edit'
    | '/profile'
    | '/portal/products'
    | '/portal/todos'
    | '/portal/posts/$postId'
    | '/portal/posts/$postId/comments'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/profile'
    | '/portal/_auth'
    | '/portal/posts'
    | '/profile/edit'
    | '/portal/'
    | '/profile/'
    | '/portal/_auth/products'
    | '/portal/_auth/todos'
    | '/portal/posts_/$postId'
    | '/portal/posts_/$postId/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/portal/posts': {
      id: '/portal/posts'
      path: '/posts'
      fullPath: '/portal/posts'
      preLoaderRoute: typeof PortalPostsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/_auth': {
      id: '/portal/_auth'
      path: ''
      fullPath: '/portal'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/posts_/$postId': {
      id: '/portal/posts_/$postId'
      path: '/posts/$postId'
      fullPath: '/portal/posts/$postId'
      preLoaderRoute: typeof PortalPostsPostIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/_auth/todos': {
      id: '/portal/_auth/todos'
      path: '/todos'
      fullPath: '/portal/todos'
      preLoaderRoute: typeof PortalAuthTodosRouteImport
      parentRoute: typeof PortalAuthRoute
    }
    '/portal/_auth/products': {
      id: '/portal/_auth/products'
      path: '/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalAuthProductsRouteImport
      parentRoute: typeof PortalAuthRoute
    }
    '/portal/posts_/$postId/comments': {
      id: '/portal/posts_/$postId/comments'
      path: '/comments'
      fullPath: '/portal/posts/$postId/comments'
      preLoaderRoute: typeof PortalPostsPostIdCommentsRouteImport
      parentRoute: typeof PortalPostsPostIdRoute
    }
  }
}

interface PortalAuthRouteChildren {
  PortalAuthProductsRoute: typeof PortalAuthProductsRoute
  PortalAuthTodosRoute: typeof PortalAuthTodosRoute
}

const PortalAuthRouteChildren: PortalAuthRouteChildren = {
  PortalAuthProductsRoute: PortalAuthProductsRoute,
  PortalAuthTodosRoute: PortalAuthTodosRoute,
}

const PortalAuthRouteWithChildren = PortalAuthRoute._addFileChildren(
  PortalAuthRouteChildren,
)

interface PortalPostsPostIdRouteChildren {
  PortalPostsPostIdCommentsRoute: typeof PortalPostsPostIdCommentsRoute
}

const PortalPostsPostIdRouteChildren: PortalPostsPostIdRouteChildren = {
  PortalPostsPostIdCommentsRoute: PortalPostsPostIdCommentsRoute,
}

const PortalPostsPostIdRouteWithChildren =
  PortalPostsPostIdRoute._addFileChildren(PortalPostsPostIdRouteChildren)

interface PortalRouteChildren {
  PortalAuthRoute: typeof PortalAuthRouteWithChildren
  PortalPostsRoute: typeof PortalPostsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalPostsPostIdRoute: typeof PortalPostsPostIdRouteWithChildren
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAuthRoute: PortalAuthRouteWithChildren,
  PortalPostsRoute: PortalPostsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalPostsPostIdRoute: PortalPostsPostIdRouteWithChildren,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
