/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PortalTodosRouteImport } from './routes/portal/todos'
import { Route as PortalPostsRouteImport } from './routes/portal/posts'
import { Route as PortalPostsPostIdRouteImport } from './routes/portal/posts.$postId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PortalTodosRoute = PortalTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostsRoute = PortalPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostsPostIdRoute = PortalPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PortalPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/portal/posts': typeof PortalPostsRouteWithChildren
  '/portal/todos': typeof PortalTodosRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portal/': typeof PortalIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/portal/posts/$postId': typeof PortalPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/posts': typeof PortalPostsRouteWithChildren
  '/portal/todos': typeof PortalTodosRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portal': typeof PortalIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/portal/posts/$postId': typeof PortalPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/portal/posts': typeof PortalPostsRouteWithChildren
  '/portal/todos': typeof PortalTodosRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portal/': typeof PortalIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/portal/posts/$postId': typeof PortalPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/profile'
    | '/portal/posts'
    | '/portal/todos'
    | '/profile/edit'
    | '/portal/'
    | '/profile/'
    | '/portal/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/posts'
    | '/portal/todos'
    | '/profile/edit'
    | '/portal'
    | '/profile'
    | '/portal/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/profile'
    | '/portal/posts'
    | '/portal/todos'
    | '/profile/edit'
    | '/portal/'
    | '/profile/'
    | '/portal/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/portal/todos': {
      id: '/portal/todos'
      path: '/todos'
      fullPath: '/portal/todos'
      preLoaderRoute: typeof PortalTodosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/posts': {
      id: '/portal/posts'
      path: '/posts'
      fullPath: '/portal/posts'
      preLoaderRoute: typeof PortalPostsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/posts/$postId': {
      id: '/portal/posts/$postId'
      path: '/$postId'
      fullPath: '/portal/posts/$postId'
      preLoaderRoute: typeof PortalPostsPostIdRouteImport
      parentRoute: typeof PortalPostsRoute
    }
  }
}

interface PortalPostsRouteChildren {
  PortalPostsPostIdRoute: typeof PortalPostsPostIdRoute
}

const PortalPostsRouteChildren: PortalPostsRouteChildren = {
  PortalPostsPostIdRoute: PortalPostsPostIdRoute,
}

const PortalPostsRouteWithChildren = PortalPostsRoute._addFileChildren(
  PortalPostsRouteChildren,
)

interface PortalRouteChildren {
  PortalPostsRoute: typeof PortalPostsRouteWithChildren
  PortalTodosRoute: typeof PortalTodosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPostsRoute: PortalPostsRouteWithChildren,
  PortalTodosRoute: PortalTodosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
